apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: to-do
spec:
  replicas: 3  #Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: to-do
  template:
    metadata:
      labels:
        app: to-do
    spec:
      containers:
        - name: to-do
          image: lucasgmarques/to-do # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster
